<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Suite]" duration-ms="230960" started-at="2019-12-28T15:26:32 IST" finished-at="2019-12-28T15:30:23 IST">
    <groups>
    </groups>
    <test name="Test(failed)" duration-ms="230960" started-at="2019-12-28T15:26:32 IST" finished-at="2019-12-28T15:30:23 IST">
      <class name="com.internetBanking.testcases.LoginTest">
        <test-method status="PASS" signature="creatingReport()[pri:0, instance:com.internetBanking.testcases.LoginTest@3b088d51]" name="creatingReport" is-config="true" duration-ms="317" started-at="2019-12-28T15:26:31 IST" finished-at="2019-12-28T15:26:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- creatingReport -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.internetBanking.testcases.LoginTest@3b088d51]" name="setup" is-config="true" duration-ms="54668" started-at="2019-12-28T15:26:32 IST" finished-at="2019-12-28T15:27:26 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTest(java.lang.String)[pri:0, instance:com.internetBanking.testcases.LoginTest@3b088d51]" name="loginTest" duration-ms="135914" started-at="2019-12-28T15:27:26 IST" finished-at="2019-12-28T15:29:42 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr239668]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.internetBanking.testcases.LoginTest@3b088d51]" name="tearDown" is-config="true" duration-ms="356" started-at="2019-12-28T15:29:42 IST" finished-at="2019-12-28T15:29:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="flushingReport()[pri:0, instance:com.internetBanking.testcases.LoginTest@3b088d51]" name="flushingReport" is-config="true" duration-ms="1222" started-at="2019-12-28T15:30:23 IST" finished-at="2019-12-28T15:30:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushingReport -->
      </class> <!-- com.internetBanking.testcases.LoginTest -->
      <class name="com.internetBanking.testcases.LoginTestDataDrivenTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.internetBanking.testcases.LoginTestDataDrivenTest@1786dec2]" name="setup" is-config="true" duration-ms="17228" started-at="2019-12-28T15:29:43 IST" finished-at="2019-12-28T15:30:00 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="logindataproviderTest(java.lang.String, java.lang.String)[pri:0, instance:com.internetBanking.testcases.LoginTestDataDrivenTest@1786dec2]" name="logindataproviderTest" duration-ms="8882" started-at="2019-12-28T15:30:03 IST" data-provider="LoginData" finished-at="2019-12-28T15:30:12 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr238114 ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ yrAqebE]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is mismatched expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Home Page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is mismatched expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Home Page]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.internetBanking.testcases.LoginTestDataDrivenTest.logindataproviderTest(LoginTestDataDrivenTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindataproviderTest -->
        <test-method status="FAIL" signature="logindataproviderTest(java.lang.String, java.lang.String)[pri:0, instance:com.internetBanking.testcases.LoginTestDataDrivenTest@1786dec2]" name="logindataproviderTest" duration-ms="9387" started-at="2019-12-28T15:30:12 IST" data-provider="LoginData" finished-at="2019-12-28T15:30:22 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr239669]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[jEnunUma]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title is mismatched expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Home Page]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title is mismatched expected [Guru99 Bank Manager HomePage] but found [Guru99 Bank Home Page]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.internetBanking.testcases.LoginTestDataDrivenTest.logindataproviderTest(LoginTestDataDrivenTest.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindataproviderTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.internetBanking.testcases.LoginTestDataDrivenTest@1786dec2]" name="closeBrowser" is-config="true" duration-ms="414" started-at="2019-12-28T15:30:22 IST" finished-at="2019-12-28T15:30:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.internetBanking.testcases.LoginTestDataDrivenTest -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
